spring:
  application:
    name: collector

collector:
  Kafka:
    uri: localhost:9092
    topics:
      actions: stats.user-actions.v1
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: ru.practicum.ewm.serializer.GeneralAvroSerializer

grpc:
  server:
    port: 0

server:
    port: 0