server:
  port: 0

spring:
  application:
    name: analyzer
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/ewm_stats"
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true


kafka:
  consumers:
    actions:
      uri: localhost:9092
      group-id: actions.analyzer
      auto-offset-reset: earliest
      enable-auto-commit: false
      consume-attempt-timeout-ms: 100
      key-deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value-deserializer: ru.practicum.ewm.deserializer.UserActionDeserializer
    similarity:
      uri: localhost:9092
      group-id: similarity.analyzer
      auto-offset-reset: earliest
      enable-auto-commit: false
      consume-attempt-timeout-ms: 100
      key-deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value-deserializer: ru.practicum.ewm.deserializer.EventSimilarityDeserializer

  topics:
    actions:
      - stats.user-actions.v1
    similarity:
      - stats.events-similarity.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext